# Lecture 2. Linear Regression
### Kirill Zakharov

In [1]:
import numpy as np
import pandas as pd

In [2]:
x1 = np.array([13, 4, 11, 20])
y = np.array([8, 5, 6, 15])

In [5]:
xmean = x1.mean()

In [6]:
ymean = y.mean()

In [16]:
th1 = sum((x1 - xmean)*(y - ymean))/130

In [17]:
th0 = ymean - 0.6307692307692307*xmean

In [15]:
(y - ymean)

array([-0.5, -3.5, -2.5,  6.5])

In [19]:
seth0 = np.sqrt(sum( (y - th0 - th1*x1)**2 )/(2))*np.sqrt(1/4 + xmean**2 / sum( (x1-xmean)**2 ))

In [20]:
seth0

2.5095026499878137

In [21]:
seth1 = np.sqrt(sum( (y - th0 - th1*x1)**2 )/(2))*np.sqrt(1/( sum( (x1-xmean)**2 )))

In [22]:
seth1

0.18889275627397964

In [24]:
int_th0 = (th0 - 4.303*seth0, th0 + 4.303*seth0)

In [25]:
int_th1 = (th1 - 4.303*seth1, th1 + 4.303*seth1)

In [23]:
1-0.05/2

0.975

In [26]:
int_th0

(-9.86762067212833, 11.729159133666792)

In [27]:
int_th1

(-0.1820362994777036, 1.443574761016165)

In [28]:
abs(th1)/seth1

3.3392981457390087

In [29]:
r2 = 1 - (sum((y-th0-th1*x1)**2))/(sum((y - ymean)**2))

In [30]:
r2

0.8479192938209331

In [32]:
rse = np.sqrt(1/(4-2) * (sum((y-th0-th1*x1)**2)))

In [33]:
rse

2.153708786828326

In [3]:
from sklearn.linear_model import LinearRegression

In [8]:
data = pd.read_csv('lin_reg.csv')

In [9]:
data

id   X   Y
0   1   3   8
1   2  18  34
2   3  17  46
3   4  24  60
4   5   7  19
5   6  19  31
6   7   8  11
7   8  10  19
8   9  20  45
9  10   6   7

In [10]:
model = LinearRegression()

In [13]:
model.fit(data.X.values.reshape(-1, 1), data.Y.values.reshape(-1, 1))

LinearRegression()

In [15]:
data.describe()

id          X          Y
count  10.00000  10.000000  10.000000
mean    5.50000  13.200000  28.000000
std     3.02765   7.192589  18.178131
min     1.00000   3.000000   7.000000
25%     3.25000   7.250000  13.000000
50%     5.50000  13.500000  25.000000
75%     7.75000  18.750000  42.250000
max    10.00000  24.000000  60.000000

In [17]:
model.coef_

array([[2.37113402]])

In [19]:
model.intercept_

array([-3.29896907])

In [22]:
model.score(data.X.values.reshape(-1, 1), data.Y.values.reshape(-1, 1))

0.8802057695907487

In [23]:
candy_df = pd.read_csv('candy_data.csv')

In [26]:
candy_df.index = candy_df.competitorname

In [27]:
candy_df

competitorname  chocolate  fruity  caramel  \
competitorname                                                             
100 Grand                          100 Grand          1       0        1   
3 Musketeers                    3 Musketeers          1       0        0   
One dime                            One dime          0       0        0   
One quarter                      One quarter          0       0        0   
Air Heads                          Air Heads          0       1        0   
...                                      ...        ...     ...      ...   
Snickers Crisper            Snickers Crisper          1       0        1   
Sour Patch Kids              Sour Patch Kids          0       1        0   
Sour Patch Tricksters  Sour Patch Tricksters          0       1        0   
Starburst                          Starburst          0       1        0   
Strawberry bon bons      Strawberry bon bons          0       1        0   

                       peanutyalmondy  nougat  crispedricewafer  hard  bar  \
competitorname                                                               
100 Grand                           0       0                 1     0    1   
3 Musketeers                        0       1                 0     0    1   
One dime                            0       0                 0     0    0   
One quarter                         0       0                 0     0    0   
Air Heads                           0       0                 0     0    0   
...                               ...     ...               ...   ...  ...   
Snickers Crisper                    1       0                 1     0    1   
Sour Patch Kids                     0       0                 0     0    0   
Sour Patch Tricksters               0       0                 0     0    0   
Starburst                           0       0                 0     0    0   
Strawberry bon bons                 0       0                 0     1    0   

                       pluribus  sugarpercent  pricepercent  winpercent  Y  
competitorname                                                              
100 Grand                     0         0.732         0.860   66.971725  1  
3 Musketeers                  0         0.604         0.511   67.602936  1  
One dime                      0         0.011         0.116   32.261086  0  
One quarter                   0         0.011         0.511   46.116505  0  
Air Heads                     0         0.906         0.511   52.341465  1  
...                         ...           ...           ...         ... ..  
Snickers Crisper              0         0.604         0.651   59.529251  1  
Sour Patch Kids               1         0.069         0.116   59.863998  1  
Sour Patch Tricksters         1         0.069         0.116   52.825947  1  
Starburst                     1         0.151         0.220   67.037628  1  
Strawberry bon bons           1         0.569         0.058   34.578991  0  

[70 rows x 14 columns]

In [28]:
candy_train = candy_df.drop(['One quarter', 'Peanut butter M&Ms'])

In [30]:
candy_train.shape

(68, 14)

In [31]:
model = LinearRegression()

In [35]:
model.fit(candy_train.iloc[:,1:-2], candy_train.iloc[:,-2])

LinearRegression()

In [36]:
model.coef_

array([ 27.96795882,  13.14255108,  -2.20589069,   8.77212418,
         3.54609405,  10.36952174,  -7.35553842,  -3.5720569 ,
        -2.20819093,  12.58284602, -10.86385976])

In [50]:
model.predict(candy_df.loc[['One quarter']].iloc[:,1:-2])

array([27.38926659])

In [51]:
model.predict(candy_df.loc[['Peanut butter M&Ms']].iloc[:,1:-2])

array([70.6426544])

In [53]:
model.predict([[0,1,1,1,1,0,1,1,0,0.505,0.618]])

/opt/anaconda3/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([44.77004263])